name: CI
on: # Here we have specified more than one triggers in list.
  - push:
      branches:
        - '!main'   # Push to this branch begins with '!' and will be skipped
        - '!release' # Push to this branch will be executed.
  - workflow_dispatch:
  push:
    branches:
      - '!main'   # Push to this branch begins with '!' and will be skipped
      - 'release' # Push to this branch will be executed.
  workflow_dispatch:  

jobs: # List of jobs that will be executed by this workflow.
  Check_Lint: # Job Name, we can also use a 'name' identifier for the same.
    runs-on: ubuntu-latest # Specify the runner where the job will be executed.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  Test_Code:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm run test
    needs: Check_Lint # 'needs' ensure that this job is ran after Check_Lint.

  Build_Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
      - name: Deploy code
        run: echo "Deploying...."
    needs: Test_Code