name: Workflow1 on push
on: [push, workflow_dispatch]
jobs:

  Check_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  Test_Code:
    runs-on: ubuntu-latest
      steps:
      - name: Run test
        run: npm run test
  
  Build_Artifact:
    runs-on: ubuntu-latest
      steps:
      - name: Build
        run: npm run build
      - name: Deploy code
        run: echo "Deploying...."