name: Simple execution
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Output current Github branch
        run: echo "GITHUB_REF_NAME: ${{ GITHUB_REF_NAME }}"
      - name: Checkout SCM
        uses: actions/checkout@v3
      - name: Display Requirements!
        run: cat requirement
