name: VariablePrint
on: [push,workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: SetVar
        id: setvar
        run: |
          MSG="Hello World!"
          echo "var=$MSG" >> $GITHUB_ENV
      - name: Print Variable
        run: echo "${{ env.var }}"